args: &args
  resourceUser: 'did:pkh:eip155:11155111:0xd231120Eea6201B142b4048cf6C86BaC2A0655D2'
  role: 'ROLE_VERIFICATION_BODY'
  policy: '0x44cc95fcac4cdc6a7c4b6d1f14643ba6ce89542b47dcba98b79ed3173efc13e6'
  context: '0x88aad075184d882a4a54fcbbb497807d2c2d84463aed96df087138385c615d04' // did:pkh:eip155:11155111:0xd231120Eea6201B142b4048cf6C86BaC2A0655D2
  numberOfPolicies: 1

workload: &workload
  module: scenario/assign-role.js

round: &round
  txNumber: 100
  rateControl:
    type: "record-rate"
    opts:
      pathTemplate: "reports/records/tx<C>_round<R>.txt"
      outputFormat: "TEXT"
      logEnd: true
      rateController:
        type: "fixed-load"
        opts:
          transactionLoad: 0.1 # 1 or 0.1?
          startingTps: 0.1

test:
  name: oac
  description: >-
    Hyperledger Caliper Benchmark of a Non-disclosing Blockchain-based Access Control for Data Sharing in Multi-Party Environments, 
    to test the backend DLT's performance with simple role assignment & session transactions.
  workers:
    number: 1
  rounds:
    - <<: *round
      label: Grant Role (#10)
      description: Grant role with ten policies
      workload:
        <<: *workload
        arguments:
          << : *args
          numberOfPolicies: 10
    - <<: *round
      label: GrantRole#8
      description: Grant role with eight policies
      workload:
        <<: *workload
        arguments:
          << : *args
          numberOfPolicies: 8
    - <<: *round
      label: Grant Role (#6)
      description: Grant role with six policies
      workload:
        <<: *workload
        arguments: *args
        numberOfPolicies: 6
    - <<: *round
      label: Grant Role (#4)
      description: Grant role with four policies
      workload:
        <<: *workload
        arguments:
          << : *args
          numberOfPolicies: 4
    - <<: *round
      label: Grant Role (#2)
      description: Grant role with two policies
      workload:
        <<: *workload
        arguments:
          << : *args
          numberOfPolicies: 2
    - <<: *round
      label: Grant Role (#0)
      description: Grant role with no policy
      workload:
        <<: *workload
        arguments: *args
        numberOfPolicies: 0
