version: "3.98"

services:
  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs
    ports:
      - "127.0.0.1:5001:5001"
      - "127.0.0.1:8081:8080"
    restart: unless-stopped
    networks:
      - oac_network
  redis:
    image: redis:alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server --save ''"]
    ports:
      - "6379:6379"
    networks:
      - oac_network
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "9001:8081"
    networks:
      - oac_network
  uni-resolver:
    image: universalresolver/uni-resolver-web:latest
    ports:
      - "8088:8080"
    platform: "linux/amd64"
    networks:
      - universal-resolver

networks:
  oac_network:
  universal-resolver:
