args: &args
  resourceUser: 'did:pkh:11155111:eip155:0xd231120Eea6201B142b4048cf6C86BaC2A0655D2'
  role: 'VERIFIER'
  policy: '0x4a99c3ee483ab2168992d7bb443539c77b520e2d0030a3ce32e95387e14b1ebc'
  context: '0xb847a0ab3c84cfd0e0d826306fdd832d83b712583d6c2659850a2f7a866c96ce'
  numberOfPolicies: 1

workload: &workload
  module: scenario/oac/assign-role.js

recordRate: &record-rate
  type: "record-rate"

recordOpts: &record-opts
  pathTemplate: "reports/records/tx<C>_round<R>.txt"
  outputFormat: "TEXT"
  logEnd: true

roundFixed: &round-fixed
  txNumber: 30
  rateControl:
    <<: *record-rate
    opts:
      <<: *record-opts
      rateController:
        type: "fixed-feedback-rate"
        opts:
          transactionLoad: 1
          startingTps: 1

roundMax: &round-max
  txDuration: 60
  rateControl:
    <<: *record-rate
    opts:
      <<: *record-opts
      rateController:
        type: "maximum-rate"
        opts:
          tps: 1
          step: 1
          sampleInterval: 10
          includeFailed: false

test:
  name: oac
  description: >-
    Hyperledger Caliper Benchmark of a Non-disclosing Blockchain-based Access Control for Data Sharing in Multi-Party Environments, 
    to test the backend DLT's performance with simple role assignment & session transactions.
  workers:
    number: 1
  rounds:
    - <<: *round-fixed
      label: AssignRole#20
      description: Grant role with twenty policies
      workload:
        <<: *workload
        arguments:
          << : *args
          numberOfPolicies: 20
    - <<: *round-fixed
      label: AssignRole#16
      description: Grant role with sixteen policies
      workload:
        <<: *workload
        arguments:
          << : *args
          numberOfPolicies: 16
    - <<: *round-fixed
      label: AssignRole#12
      description: Grant role with twelve policies
      workload:
        <<: *workload
        arguments:
          << : *args
          numberOfPolicies: 12
    - <<: *round-fixed
      label: AssignRole#8
      description: Grant role with eight policies
      workload:
        <<: *workload
        arguments:
          << : *args
          numberOfPolicies: 8
    - <<: *round-fixed
      label: AssignRole#4
      description: Grant role with four policies
      workload:
        <<: *workload
        arguments:
          << : *args
          numberOfPolicies: 4
    - <<: *round-fixed
      label: AssignRole#1
      description: Grant role with one policy
      workload:
        <<: *workload
        arguments: *args
    - <<: *round-max
      label: AssignRoleMax#20
      description: Grant role for max rate with twenty policy
      workload:
        <<: *workload
        arguments:
          << : *args
          numberOfPolicies: 20
    - <<: *round-max
      label: AssignRoleMax#1
      description: Grant role for max rate with one policy
      workload:
        <<: *workload
        arguments:
          << : *args
          numberOfPolicies: 1
#    - label: start-session
#      description: Start a session through the deployed contract.
#      txNumber: 50
#      rateControl:
#        type: fixed-rate
#        opts:
#          tps: 5
#      workload:
#        module: scenario/simple/start-session.js
#        arguments: *args
