oacArgs: &oac-args
  resourceUser: 'did:pkh:eip115:0xc0A8e4D217eB85b812aeb1226fAb6F588943C2C2'
  role: 'VERIFIER_ROLE'
  policy: 'POLICY_ID'
  numberOfPolicies: 1
test:
  name: oac
  description: >-
    Hyperledger Caliper Benchmark of 'Non-disclosing Blockchain-based Access Control for Data Sharing in Multi-Party Environments', 
    to test the backend DLT's performance with simple role assignment & session transactions.
  workers:
    number: 1
  rounds:
    - label: assign-role
      description: Role assignment through the deployed contract.
      txNumber: 50
      rateControl:
        type: fixed-rate
        opts:
          tps: 5
      workload:
        module: scenario/oac/assign-role.js
        arguments: *oac-args
    - label: start-session
      description: Start a session through the deployed contract.
      txNumber: 50
      rateControl:
        type: fixed-rate
        opts:
          tps: 5
      workload:
        module: scenario/simple/start-session.js
        arguments: *oac-args
