oacArgs: &oac-args
  resourceUser: 'did:pkh:11155111:eip155:0xd231120Eea6201B142b4048cf6C86BaC2A0655D2'
  role: 'VERIFIER'
  policy: '0x4a99c3ee483ab2168992d7bb443539c77b520e2d0030a3ce32e95387e14b1ebc'
  context: '0xb847a0ab3c84cfd0e0d826306fdd832d83b712583d6c2659850a2f7a866c96ce'
  numberOfPolicies: 1

grWorkload: &gr-workload
    module: scenario/oac/assign-role.js

grRound: &gr-round
    txNumber: 20
    rateControl:
      type: fixed-load
      opts:
        transactionLoad: 1,
        startingTps: 1

test:
  name: oac
  description: >-
    Hyperledger Caliper Benchmark of a Non-disclosing Blockchain-based Access Control for Data Sharing in Multi-Party Environments, 
    to test the backend DLT's performance with simple role assignment & session transactions.
  workers:
    number: 1
  rounds:
    - <<: *gr-round
      label: grantRole#1
      description: Grant role with one policy
      workload:
        <<: *gr-workload
        arguments: *oac-args
    - <<: *gr-round
      label: grantRole#2
      description: Grant role with two policies
      workload:
        <<: *gr-workload
        arguments:
          << : *oac-args
          numberOfPolicies: 2
    - <<: *gr-round
      label: grantRole#3
      description: Grant role with three policies
      workload:
        <<: *gr-workload
        arguments:
          << : *oac-args
          numberOfPolicies: 3
    - <<: *gr-round
      label: grantRole#4
      description: Grant role with four policies
      workload:
        <<: *gr-workload
        arguments:
          << : *oac-args
          numberOfPolicies: 4
    - <<: *gr-round
      label: grantRole#5
      description: Grant role with five policies
      workload:
        <<: *gr-workload
        arguments:
          << : *oac-args
          numberOfPolicies: 5
    - <<: *gr-round
      label: grantRole#6
      description: Grant role with six policies
      workload:
        <<: *gr-workload
        arguments:
          << : *oac-args
          numberOfPolicies: 6
    - <<: *gr-round
      label: grantRole#7
      description: Grant role with seven policies
      workload:
        <<: *gr-workload
        arguments:
          << : *oac-args
          numberOfPolicies: 7
    - <<: *gr-round
      label: grantRole#8
      description: Grant role with eight policies
      workload:
        <<: *gr-workload
        arguments:
          << : *oac-args
          numberOfPolicies: 8
    - <<: *gr-round
      label: grantRole#9
      description: Grant role with nine policies
      workload:
        <<: *gr-workload
        arguments:
          << : *oac-args
          numberOfPolicies: 9
    - <<: *gr-round
      label: grantRole#10
      description: Grant role with ten policies
      workload:
        <<: *gr-workload
        arguments:
          << : *oac-args
          numberOfPolicies: 10
    - <<: *gr-round
      label: grantRole#11
      description: Grant role with eleven policies
      workload:
        <<: *gr-workload
        arguments:
          << : *oac-args
          numberOfPolicies: 11
    - <<: *gr-round
      label: grantRole#12
      description: Grant role with twelve policies
      workload:
        <<: *gr-workload
        arguments:
          << : *oac-args
          numberOfPolicies: 12
    - <<: *gr-round
      label: grantRole#13
      description: Grant role with thirteen policies
      workload:
        <<: *gr-workload
        arguments:
          << : *oac-args
          numberOfPolicies: 13
#    - label: start-session
#      description: Start a session through the deployed contract.
#      txNumber: 50
#      rateControl:
#        type: fixed-rate
#        opts:
#          tps: 5
#      workload:
#        module: scenario/simple/start-session.js
#        arguments: *oac-args
