version: "3"
services:
  node:
    build: .
    image: caliper-ethereum
    container_name: ethereum
    volumes:
      - ./keys:/root/.ethereum/keystore
    ports:
      - "8546:8546"
    command: --unlock 0xc0A8e4D217eB85b812aeb1226fAb6F588943C2C2 --password /root/.ethereum/keystore/password --mine --miner.etherbase 0xc0A8e4D217eB85b812aeb1226fAb6F588943C2C2 --ws --ws.addr 0.0.0.0 --ws.origins='*' --ws.api admin,eth,miner,personal,web3 --allow-insecure-unlock --nodiscover --miner.gasprice 1
